### ISSUE TITLE
How to set initial value and update it from outside?

### ISSUE THREAD

**Issue by vasilich6107** [rodrigobastosv/fancy_password_field#13]
Hi
Text editing controller allow to set/update the value in textfield
How to do it in this package with `FancyPasswordController`?

**Comment by rodrigobastosv** [comment]
Hi @vasilich6107 , 

Turns out I had forgotten to add the controller property. Everything should now be working the same way as Flutter's default `TextFormField`. Just get the 1.0.2 version from pub.dev :).

You can set the initial value using the `initialValue` property, or passing your own `TextEditingController`.

I also added an example in the samples directory with a simple usage (`sample_initial_value.dart`)

Thanks again!

Will close the issue but feel free to reopen if needed!

**Comment by vasilich6107** [comment]
@rodrigobastosv 
created wrapper for `reactive_forms` based on your widget
https://pub.dev/packages/reactive_fancy_password_field

Thanks for collaboration

**Comment by rodrigobastosv** [comment]
Thanks @vasilich6107!
