### ISSUE TITLE
Change showPasswordIcon color

### ISSUE THREAD

**Issue by jeffjoslin** [rodrigobastosv/fancy_password_field#17]
Hello and thank you for this great flutter package!

Question: Is there a way to change the showPasswordIcon color?

Thank you!

**Comment by rodrigobastosv** [comment]
Hey @jeffjoslin , thanks very much!

The ideal way of changing this is passing your own InputDecoration, with your own suffixIcon, for example. That way you have full controll of what to display.

I could change the api to receive an Icon as oppose to receiving an IconData, but i am not really sure if that would be better or not.

**Comment by matthieurosset** [comment]
Thanks a lot for your package @rodrigobastosv !

Icon instead of IconData will be exactly what I was looking for.
Overriding "suffixIcon" is more painful because you have to keep another state above your component (just to store your _hidepassword boolean). 

With IconData, I can override size and color. No need more !

**Comment by rodrigobastosv** [comment]
Yeah guys, i am sold that is better just pass an Icon instead of IconData. I will make this change later today. Thanks a lot!

**Comment by rodrigobastosv** [comment]
Just uploaded the 2.0.0 with this request.

Thank you very much!

**Comment by jeffjoslin** [comment]
Fantastic. Thank you again for this great package and you fast response!
