### ISSUE TITLE
Unable to use fancy_password_field with font_awesome_flutter pro version

### ISSUE THREAD

**Issue by caitlin-melon** [rodrigobastosv/fancy_password_field#25]
When trying to add the `fancy_password_field` package, we get the following error: 

```So, because kiasma depends on both font_awesome_flutter from path and fancy_password_field any, version solving failed```

We currently use the pro version of font awesome and host it locally in a private repo. Just wondering if you had any plans to be able to make it possible to use `fancy_password_field` in combination with `font_awesome_flutter` from path without us needing to make this repo public?

**Comment by rodrigobastosv** [comment]
Hey @caitlin-melon , thanks for using this package!

The package was `font_awesome_flutter` only to display the password icons on `DefaultShowHidePasswordButton`. Since you can always configure with your default icons, i decided to remove the `font_awesome_flutter` dependency from the project.

You should be able to use the package now. Please get the `2.0.6` version on pub.dev.

Feel free to reopen the issue if needed.

Thanks!

**Comment by caitlin-melon** [comment]
Thank you so much! Appreciate it 😃
